[package]
name = "peace"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.4.1", features = ["concolor", "auto-color"] }
chumsky = { git = "https://github.com/zesterer/chumsky", version = "1.0.0-alpha.7" }
lelwel = "0.6.2"
nom = "7.1.3"
